### ISSUE TITLE
mask[i] is a one-element list

### ISSUE THREAD

**Issue by nk53** [losonczylab/sima#120]
The following code:
>import sima
>import sima.segment
>
>video = "image.tif"
>analysis_dir = "stica_test.sima"
>
>seq = sima.Sequence.create('TIFF', 'original.tif')
>dataset = sima.ImagingDataset([seq], analysis_dir)
>
>stica = sima.segment.STICA(components=5, overlap_per=0.5)
>rois = dataset.segment(stica, label="stICA ROIs")

Leads to the following error:
>Traceback (most recent call last):
>  File "./stica_test.py", line 15, in \<module\>
>    rois = dataset.segment(stica, label="stICA ROIs")
>  File "/Library/Python/2.7/site-packages/sima/imaging.py", line 717, in segment
>    rois = strategy.segment(self)
>  File "/Library/Python/2.7/site-packages/sima/segment/segment.py", line 38, in segment
>    rois = self._segment(dataset)
>  File "/Library/Python/2.7/site-packages/sima/segment/segment.py", line 79, in checked_func
>    return func(self, dataset)
>  File "/Library/Python/2.7/site-packages/sima/segment/stica.py", line 382, in _segment
>    rois, percent_overlap=self._params.overlap_per)
>  File "/Library/Python/2.7/site-packages/sima/segment/segment.py", line 163, in _remove_overlapping
>    overlap = np.logical_and(rois[i].mask.toarray(),
>AttributeError: 'list' object has no attribute 'toarray'

In this case, `rois[i].mask` is a `[<490x490 sparse matrix of type '<type 'numpy.bool_'>'
with 246 stored elements in LInked List format>]`

**Comment by pkaifosh** [comment]
Hi. I just pushed a change that should address this. Can you pull your checkout of the repository and let me know if it works now?

**Comment by pkaifosh** [comment]
Sorry, I realize the fix may have been erroneous. Give me a second before trying again.

**Comment by pkaifosh** [comment]
@nk53 OK. It should be good now. Sorry about that. We've adjusted one of our test cases now to make sure this stays working going forward.

**Comment by nk53** [comment]
Now I just get `ImportError: cannot import name _motion` from `motion.py`

**Comment by pkaifosh** [comment]
This is probably a problem with your installation. You probably need to rerun the setup.py script.

Can you send the full error trace message?

**Comment by nk53** [comment]
I'm not sure how I'm supposed to run setup.py differently. I first removed the sima package from site-packages, then ran `python setup.py clean` (in another try, I just removed the build directory), then `python setup.py build` and `sudo python setup.py install`. Isn't this how I'm supposed to do it?

Here's the full error message, which occurs when importing sima:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sima/__init__.py", line 7, in <module>
    from sima.sequence import Sequence
  File "sima/sequence.py", line 69, in <module>
    from sima.motion._motion import _align_frame
  File "sima/motion/__init__.py", line 5, in <module>
    from .motion import MotionEstimationStrategy, ResonantCorrection
  File "sima/motion/motion.py", line 14, in <module>
    from . import _motion as mc
ImportError: cannot import name _motion

**Comment by pkaifosh** [comment]
What are the contents of your sima/sima and sima/sima/motion directories? Also, fee free to join our chat if you want to discuss this more quickly: https://gitter.im/losonczylab/sima

**Comment by nerduno** [comment]
I'm getting this same import error (ImportError: cannot import name _motion), after having upgraded to version 1.0.3 using pip on Ubuntu.  

The directory .../site-packages/sima/motion does not contain _motion.  I'm guessing this has something to do with Cython compilation.

**Comment by pkaifosh** [comment]
Sorry about this. There seems to be something off with the packaging for that version. We'll release a new version very soon and hopefully that will fix it. In the mean time, you can download the .egg file from pypi and copy the .so file into the appropriate location (.../site-packages/sima/motion/_motion.so). You may have to do similar things for other .so files if they were not included.

**Comment by nerduno** [comment]
Thanks for the suggestion. However that resulted in:

**Comment by pkaifosh** [comment]
Building from source should be fine. You can clone the sima git repo and checkout version 1.0.3.

**Comment by nerduno** [comment]
Thank Patrick.  I checked out version 1.0.3, and I'm now getting the follow error when trying to create an imaging dataset:

/usr/local/lib/python2.7/site-packages/sima/imaging.pyc in <genexpr>((s,))
    124             except KeyError:
    125                 pass
--> 126         elif all(isinstance(s, sima.Sequence) for s in sequences):
    127             self.savedir = savedir
    128             self.sequences = sequences

AttributeError: 'module' object has no attribute 'Sequence'

**Comment by pkaifosh** [comment]
Hi, can you join the gitter chat to figure this out quickly?

https://gitter.im/losonczylab/sima?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by pkaifosh** [comment]
I'm guessing it has something to do with conflicting version installed, so I'd like to go back and forth quickly about what is in the install directory, etc...

**Comment by pkaifosh** [comment]
What are the contents of this directory: /usr/local/lib/python2.7/site-packages/sima ?

**Comment by pkaifosh** [comment]
Here is how I just installed from source and then tested SIMA 1.0.3 on a clean virtual environment on an ubuntu machine. The tests pass, indicating that no problems occurred when creating datasets. Did you do anything differently?

```
(py2.venv)patrick@patrick-HP-Folio-13-Notebook-PC:~/code-checkouts/sima$ git checkout 1.0.3 Note: checking out '1.0.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at e340a2c... 1.0.3 version numbers
(py2.venv)patrick@patrick-HP-Folio-13-Notebook-PC:~/code-checkouts/sima$ python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
copying sima/imaging.py -> build/lib.linux-x86_64-2.7/sima
copying sima/sequence.py -> build/lib.linux-x86_64-2.7/sima
copying sima/imaging_parameters.py -> build/lib.linux-x86_64-2.7/sima
copying sima/__init__.py -> build/lib.linux-x86_64-2.7/sima
copying sima/extract.py -> build/lib.linux-x86_64-2.7/sima
copying sima/ROI.py -> build/lib.linux-x86_64-2.7/sima
copying sima/misc/convert.py -> build/lib.linux-x86_64-2.7/sima/misc
copying sima/misc/imagej.py -> build/lib.linux-x86_64-2.7/sima/misc
copying sima/misc/align.py -> build/lib.linux-x86_64-2.7/sima/misc
copying sima/misc/tifffile.py -> build/lib.linux-x86_64-2.7/sima/misc
copying sima/misc/__init__.py -> build/lib.linux-x86_64-2.7/sima/misc
copying sima/motion/motion.py -> build/lib.linux-x86_64-2.7/sima/motion
copying sima/motion/hmm.py -> build/lib.linux-x86_64-2.7/sima/motion
copying sima/motion/transform.py -> build/lib.linux-x86_64-2.7/sima/motion
copying sima/motion/__init__.py -> build/lib.linux-x86_64-2.7/sima/motion
copying sima/motion/frame_align.py -> build/lib.linux-x86_64-2.7/sima/motion
package init file 'sima/motion/tests/__init__.py' not found (or not a regular file)
copying sima/motion/tests/test_hmm.py -> build/lib.linux-x86_64-2.7/sima/motion/tests
copying sima/motion/tests/test_frame_align.py -> build/lib.linux-x86_64-2.7/sima/motion/tests
copying sima/segment/segment.py -> build/lib.linux-x86_64-2.7/sima/segment
copying sima/segment/ca1pc.py -> build/lib.linux-x86_64-2.7/sima/segment
copying sima/segment/normcut.py -> build/lib.linux-x86_64-2.7/sima/segment
copying sima/segment/__init__.py -> build/lib.linux-x86_64-2.7/sima/segment
copying sima/segment/stica.py -> build/lib.linux-x86_64-2.7/sima/segment
copying sima/segment/oPCA.py -> build/lib.linux-x86_64-2.7/sima/segment
package init file 'sima/segment/tests/__init__.py' not found (or not a regular file)
copying sima/segment/tests/test_segment.py -> build/lib.linux-x86_64-2.7/sima/segment/tests
copying sima/tests/test_ROI.py -> build/lib.linux-x86_64-2.7/sima/tests
copying sima/tests/test_sequence.py -> build/lib.linux-x86_64-2.7/sima/tests
copying sima/tests/test_imaging.py -> build/lib.linux-x86_64-2.7/sima/tests
copying sima/tests/test_extract.py -> build/lib.linux-x86_64-2.7/sima/tests
package init file 'sima/motion/tests/__init__.py' not found (or not a regular file)
package init file 'sima/segment/tests/__init__.py' not found (or not a regular file)
running build_ext
running install_lib
copying build/lib.linux-x86_64-2.7/sima/imaging.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima
copying build/lib.linux-x86_64-2.7/sima/segment/segment.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment
copying build/lib.linux-x86_64-2.7/sima/segment/ca1pc.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment
copying build/lib.linux-x86_64-2.7/sima/segment/normcut.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment
copying build/lib.linux-x86_64-2.7/sima/segment/_opca.so -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment
copying build/lib.linux-x86_64-2.7/sima/segment/tests/test_segment.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment/tests
copying build/lib.linux-x86_64-2.7/sima/segment/__init__.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment
copying build/lib.linux-x86_64-2.7/sima/segment/stica.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment
copying build/lib.linux-x86_64-2.7/sima/segment/oPCA.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment
copying build/lib.linux-x86_64-2.7/sima/sequence.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima
copying build/lib.linux-x86_64-2.7/sima/tests/test_ROI.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/tests
copying build/lib.linux-x86_64-2.7/sima/tests/test_sequence.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/tests
copying build/lib.linux-x86_64-2.7/sima/tests/test_imaging.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/tests
copying build/lib.linux-x86_64-2.7/sima/tests/test_extract.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/tests
copying build/lib.linux-x86_64-2.7/sima/misc/convert.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc
copying build/lib.linux-x86_64-2.7/sima/misc/imagej.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc
copying build/lib.linux-x86_64-2.7/sima/misc/align.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc
copying build/lib.linux-x86_64-2.7/sima/misc/tifffile.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc
copying build/lib.linux-x86_64-2.7/sima/misc/__init__.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc
copying build/lib.linux-x86_64-2.7/sima/imaging_parameters.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima
copying build/lib.linux-x86_64-2.7/sima/extract.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima
copying build/lib.linux-x86_64-2.7/sima/ROI.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima
copying build/lib.linux-x86_64-2.7/sima/motion/motion.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion
copying build/lib.linux-x86_64-2.7/sima/motion/hmm.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion
copying build/lib.linux-x86_64-2.7/sima/motion/transform.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion
copying build/lib.linux-x86_64-2.7/sima/motion/tests/test_hmm.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/tests
copying build/lib.linux-x86_64-2.7/sima/motion/tests/test_frame_align.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/tests
copying build/lib.linux-x86_64-2.7/sima/motion/__init__.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion
copying build/lib.linux-x86_64-2.7/sima/motion/frame_align.py -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion
copying build/lib.linux-x86_64-2.7/sima/motion/_motion.so -> /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/imaging.py to imaging.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment/segment.py to segment.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment/ca1pc.py to ca1pc.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment/normcut.py to normcut.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment/tests/test_segment.py to test_segment.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment/__init__.py to __init__.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment/stica.py to stica.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/segment/oPCA.py to oPCA.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/sequence.py to sequence.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/tests/test_ROI.py to test_ROI.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/tests/test_sequence.py to test_sequence.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/tests/test_imaging.py to test_imaging.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/tests/test_extract.py to test_extract.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc/convert.py to convert.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc/imagej.py to imagej.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc/align.py to align.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc/tifffile.py to tifffile.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/misc/__init__.py to __init__.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/imaging_parameters.py to imaging_parameters.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/extract.py to extract.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/ROI.py to ROI.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/motion.py to motion.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/hmm.py to hmm.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/transform.py to transform.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/tests/test_hmm.py to test_hmm.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/tests/test_frame_align.py to test_frame_align.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/__init__.py to __init__.pyc
byte-compiling /home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/frame_align.py to frame_align.pyc
running install_egg_info
removing '/home/patrick/py2.venv/lib/python2.7/site-packages/sima-1.0.3-py2.7.egg-info' (and everything under it)
Writing /home/patrick/py2.venv/lib/python2.7/site-packages/sima-1.0.3-py2.7.egg-info
(py2.venv)patrick@patrick-HP-Folio-13-Notebook-PC:~/code-checkouts/sima$ 
(py2.venv)patrick@patrick-HP-Folio-13-Notebook-PC:~/code-checkouts/sima$ 
(py2.venv)patrick@patrick-HP-Folio-13-Notebook-PC:~/code-checkouts/sima$ ls
appveyor      CREDITS.rst  INSTALL.rst  pylintrc    runtests.py  sima.egg-info
appveyor.yml  doc          license.txt  pytest.ini  setup.py     venv
build         examples     MANIFEST.in  README.rst  sima
(py2.venv)patrick@patrick-HP-Folio-13-Notebook-PC:~/code-checkouts/sima$ ipython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: exit()
(py2.venv)patrick@patrick-HP-Folio-13-Notebook-PC:~/code-checkouts/sima$ ipython
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sima

In [2]: sima.test()
Running unit tests for sima
NumPy version 1.8.2
NumPy is installed in /usr/lib/python2.7/dist-packages/numpy
Python version 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
nose version 1.3.1
....K./usr/lib/python2.7/dist-packages/numpy/lib/nanfunctions.py:607: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)
/home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/frame_align.py:496: UserWarning: Could not align all frames.
  warnings.warn('Could not align all frames.')
........./home/patrick/py2.venv/lib/python2.7/site-packages/sima/motion/hmm.py:770: UserWarning: No finite observation probabilities.
  warnings.warn('No finite observation probabilities.')
.../home/patrick/py2.venv/lib/python2.7/site-packages/sima/ROI.py:660: UserWarning: Polygon initialized without z-coordinate. Assigning to zeroth plane (z = 0)
  'Assigning to zeroth plane (z = 0)')
........./usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
..../usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/linalg/dsolve/linsolve.py:335: DeprecationWarning: scipy.sparse.linalg.dsolve.umfpack will be removed, install scikits.umfpack instead
  ' install scikits.umfpack instead', DeprecationWarning)
...........
----------------------------------------------------------------------
Ran 42 tests in 44.227s

OK (KNOWNFAIL=1)
Out[2]: <nose.result.TextTestResult run=42 errors=0 failures=0>
```

**Comment by nerduno** [comment]
I got it working.  Thank you for your help.  After installed from source, I believe I had not reloaded all the necessary packages into my kernel.  Restarting the kernel did the trick.

**Comment by pkaifosh** [comment]
@nerduno I tested installing the latest version of SIMA (1.1.0, released today) on Ubuntu with pip, and it seemed to go smoothly.

**Comment by nerduno** [comment]
thanks for the info.

question: I'm considering using sima's motion correction on data that has
some frame averaging.  Thus the row-wise HMM doesn't make much sense.  Have
you tried the pixel-wise HMM on this type of data?

**Comment by pkaifosh** [comment]
Could you describe the nature of the averaging, i.e. what is being averaged?

Also, perhaps we should move this discussion to the form so that it's easier for people with similar inquiries to find: https://groups.google.com/forum/#!forum/sima-users
