### ISSUE TITLE
Importing sima failure

### ISSUE THREAD

**Issue by celialoriette** [losonczylab/sima#129]
Hi,
I just spent my two last days trying to import sima...
I get this :

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 566, in write_error
    self.shell.write_error(self.get_stderr())
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 272, in get_stderr
    return self.transcode(qba)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 258, in transcode
    return to_text_string(qba.data(), 'utf8')
  File "C:\Python27\lib\site-packages\spyderlib\py3compat.py", line 134, in to_text_string
    return unicode(obj, encoding)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 1095: invalid continuation byte
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\pythonshell.py", line 566, in write_error
    self.shell.write_error(self.get_stderr())
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 272, in get_stderr
    return self.transcode(qba)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\baseshell.py", line 258, in transcode
    return to_text_string(qba.data(), 'utf8')
  File "C:\Python27\lib\site-packages\spyderlib\py3compat.py", line 134, in to_text_string
    return unicode(obj, encoding)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 1095: invalid continuation byte

Somebody could help me ?
Thanks
Celia

**Comment by pkaifosh** [comment]
Hi Celia,

I don't see anything in the traceback that you pasted that mentions SIMA; it seems there is something funny happening with Spyder. Have you tried running in a standard python shell instead of Spyder? If the error persists, can you send the code that you ran along with the commands that you ran to produce the error?

Also, what version of SIMA are you running, and what method did you use to install it?

**Comment by celialoriette** [comment]
> Hi Celia,
>
> I don't see anything in the traceback that you pasted that mentions SIMA;
> it seems there is something funny happening with Spyder. Have you tried
> running in a standard python shell instead of Spyder? If the error
> persists, can you send the code that you ran along with the commands that
> you ran to produce the error?
>
> Also, what version of SIMA are you running, and what method did you use to
> install it?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/losonczylab/sima/issues/129#issuecomment-75240905


Hi
Thanks for this quick answer !
With another interpreter I have :

>>> import sima
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\sima\__init__.py", line
    from sima.imaging import ImagingDataset
  File "C:\Python27\lib\site-packages\sima\imaging.py", line
    from sima.ROI import ROIList
  File "C:\Python27\lib\site-packages\sima\ROI.py", line 24,
    from shapely.geometry import MultiPolygon, Polygon, Point
  File "C:\Python27\lib\site-packages\shapely\geometry\__init
<module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Python27\lib\site-packages\shapely\geometry\base.p
ule>
    from shapely.coords import CoordinateSequence
  File "C:\Python27\lib\site-packages\shapely\coords.py", lin
    from shapely.geos import lgeos
  File "C:\Python27\lib\site-packages\shapely\geos.py", line
    _lgeos = CDLL("geos.dll")
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __i
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Le module sp�cifi� est introuvable

I am using the 1.0.3 sima version installed with pip install sima without
trouble.

**Comment by pkaifosh** [comment]
OK. The problem boils down to a problem with your installation of the shapely dependency. How did you install it? I would recommend completely removing shapely and then installing it with the .whl from this site: http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

Let me know if that fixes things.

**Comment by celialoriette** [comment]
> OK. The problem boils down to a problem with your installation of the
> shapely dependency. How did you install it? I would recommend completely
> removing shapely and then installing it with the .whl from this site:
> http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely
>
> Let me know if that fixes things.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/losonczylab/sima/issues/129#issuecomment-75244609

Thanks !
Yes it's fixed thanks =)
I am now on trying importing my tiff data ...
Thanks again
Celia

**Comment by celialoriette** [comment]
> OK. The problem boils down to a problem with your installation of the
> shapely dependency. How did you install it? I would recommend completely
> removing shapely and then installing it with the .whl from this site:
> http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely
>
> Let me know if that fixes things.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/losonczylab/sima/issues/129#issuecomment-75244609


Hi again
I thought it was fixed but seems not.
Now, the computer doesn't say anything while I import sima
but when I try to import sima.something I need to use my tiff files,
python doesn't find it, as if sima wasn't installed ?

>>> import sima.Sequence.create
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Sequence.create
>>> from sima.iterables import MutliPageTIFF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named iterables
>>> import sima
>>> from sima.iterables import MutliPageTIFF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named iterables
>>> import sima.iterables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named iterables

**Comment by pkaifosh** [comment]
You can't import the create method like that. Instead, just do:
```
import sima

sequence = sima.Sequence.create(...)
```

If this is confusing, you may want to read up on python imports and classes.

The "Iterables" class no longer exist in versions 1.x of SIMA, so make sure that you are following the current tutorial and not that of an old version.
