### ISSUE TITLE
 for u, v, w, x in pixel_pairs IndexError: index 30 is out of bounds for axis 1 with size 30

### ISSUE THREAD

**Issue by aprasad1993** [losonczylab/sima#162]
I am trying to run the basic example which has been provided on the documentation page. I get the output file names but I am not able to plot the Graphs. 

Output filenames:
[[['workflow_data/Cycle01_Ch1_corrected.tif', 'workflow_data/Cycle01_Ch2_corrected.tif']], [['workflow_data/Cycle02_Ch1_corrected.tif', 'workflow_data/Cycle02_Ch2_corrected.tif']], [['workflow_data/Cycle03_Ch1_corrected.tif', 'workflow_data/Cycle03_Ch2_corrected.tif']], [['workflow_data/Cycle04_Ch1_corrected.tif', 'workflow_data/Cycle04_Ch2_corrected.tif']], [['workflow_data/Cycle05_Ch1_corrected.tif', 'workflow_data/Cycle05_Ch2_corrected.tif']], [['workflow_data/Cycle06_Ch1_corrected.tif', 'workflow_data/Cycle06_Ch2_corrected.tif']], [['workflow_data/Cycle07_Ch1_corrected.tif', 'workflow_data/Cycle07_Ch2_corrected.tif']], [['workflow_data/Cycle08_Ch1_corrected.tif', 'workflow_data/Cycle08_Ch2_corrected.tif']], [['workflow_data/Cycle09_Ch1_corrected.tif', 'workflow_data/Cycle09_Ch2_corrected.tif']], [['workflow_data/Cycle10_Ch1_corrected.tif', 'workflow_data/Cycle10_Ch2_corrected.tif']], [['workflow_data/Cycle11_Ch1_corrected.tif', 'workflow_data/Cycle11_Ch2_corrected.tif']], [['workflow_data/Cycle12_Ch1_corrected.tif', 'workflow_data/Cycle12_Ch2_corrected.tif']], [['workflow_data/Cycle13_Ch1_corrected.tif', 'workflow_data/Cycle13_Ch2_corrected.tif']], [['workflow_data/Cycle14_Ch1_corrected.tif', 'workflow_data/Cycle14_Ch2_corrected.tif']], [['workflow_data/Cycle15_Ch1_corrected.tif', 'workflow_data/Cycle15_Ch2_corrected.tif']]]
Continue? (y/n): y
Traceback (most recent call last):
  File "biomed.py", line 76, in <module>
    dataset.segment(segmentation_approach, 'auto_ROIs')
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/imaging.py", line 766, in segment
    rois = strategy.segment(self)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 44, in segment
    rois = self._segment(dataset)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 86, in checked_func
    return func(self, dataset)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/ca1pc.py", line 265, in _segment
    return self._normcut_method.segment(dataset)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 44, in segment
    rois = self._segment(dataset)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 86, in checked_func
    return func(self, dataset)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 485, in _segment
    affinity = params['affinity_method'].calculate(dataset)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 391, in calculate
    self._setup(dataset)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/ca1pc.py", line 152, in _setup
    super(AffinityMatrixCA1PC, self)._setup(dataset)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 388, in _setup
    self._correlations = self._calculate_correlations(dataset)
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 378, in _calculate_correlations
    num_pcs=self._params['num_pcs'], verbose=self._params['verbose'])
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 299, in _offset_corrs
    for u, v, w, x in pixel_pairs
  File "/Users/anurag_prasad/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 299, in <dictcomp>
    for u, v, w, x in pixel_pairs
IndexError: index 30 is out of bounds for axis 1 with size 30

**Comment by jzaremba** [comment]
Thanks for the report.

I just checked the master branch and 1.2.0 and I'm unable to reproduce the issue you are having. What version of SIMA are you running?
Does sima/examples/workflow.py work for you?
The example workflow should also be the same as the example in the documentation tutorial.

**Comment by aprasad1993** [comment]
I installed the latest version of SIMA using pip. 

The end to end example provided in the tutorial is what I am trying to run.

**Comment by pkaifosh** [comment]
Can you please send the complete contents of biomed.py and the output of the following commands:

```
$ python -c "import sima; print sima.__version__"
$ python biomed.py
```

**Comment by pkaifosh** [comment]
I'm closing this issue since I haven't heard back and since we were unable to reproduce the problem.
