### ISSUE TITLE
 .sima savedir interferes with ImagingDataset that attempts to overwrite it but has larger frames

### ISSUE THREAD

**Issue by eflister** [losonczylab/sima#177]
```
>>> type(d)
<type 'numpy.ndarray'>
>>> d.shape
(100, 1, 10, 20, 1) # (num_frames, num_planes, num_rows, num_columns, num_channels)
>>> d.dtype
dtype('<f8')

>>> seq = sima.Sequence.create('ndarray', d)
>>> seq.shape
(100, 1, 10, 20, 1) 
```
http://www.losonczylab.org/sima/1.2/tutorial.html#creating-an-imagingdataset-object
says:
"raw imaging data used to initialize the ImagingDataset object must be packaged into a list of lists, whose first index runs over the cycles and whose second index runs over the channels"

but
```
>>> dataset = sima.ImagingDataset([[seq]], dataset_path)
TypeError: ImagingDataset objects must be initialized with a list of sequences.
```
and either of these:
```
>>> dataset = sima.ImagingDataset([sima.Sequence.join(seq)], dataset_path)
>>> dataset = sima.ImagingDataset([                   seq ], dataset_path)
```
gives this, which looks right:
```
<ImagingDataset: num_sequences=1, frame_shape=(1, 10, 20, 1), num_frames=100> 
# frame_shape is (num_planes, num_rows, num_columns, num_channels)
```
but either
```
>>> segmentation_approach = sima.segment.PlaneCA1PC(
...     channel='GCaMP',
...     num_pcs=30,
...     max_dist=(3, 6),
...     spatial_decay=(3, 6),
...     cut_max_pen=0.10,
...     cut_min_size=50,
...     cut_max_size=150,
...     x_diameter=14,
...     y_diameter=7,
...     circularity_threhold=.5,
...     min_roi_size=20,
...     min_cut_size=40
... )
```
or 
```
>>> segmentation_approach = sima.segment.STICA(components=2, verbose=True)
```
with
```
>>> rois = dataset.segment(segmentation_approach, 'auto_ROIs')
```
errors -- 

for STICA:
```
performing PCA...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/imaging.py", line 768, in segment
    rois = strategy.segment(self)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 46, in segment
    rois = self._segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/stica.py", line 195, in _segment
    dataset, channel, components[-1] + 1, path=pca_path)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/oPCA.py", line 291, in dataset_opca
    DatasetIterable(dataset, ch), num_pcs=num_pcs, verbose=verbose)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/oPCA.py", line 89, in EM_oPCA
    for X in (data):
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/oPCA.py", line 244, in __iter__
    frame[..., self.channel].reshape(-1) - self.means)
ValueError: operands could not be broadcast together with shapes (200,) (20,) 
```
for CA1PC:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/imaging.py", line 768, in segment
    rois = strategy.segment(self)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 46, in segment
    rois = self._segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 88, in checked_func
    return func(self, dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/ca1pc.py", line 265, in _segment
    return self._normcut_method.segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 46, in segment
    rois = self._segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 88, in checked_func
    return func(self, dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 485, in _segment
    affinity = params['affinity_method'].calculate(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 391, in calculate
    self._setup(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/ca1pc.py", line 152, in _setup
    super(AffinityMatrixCA1PC, self)._setup(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 388, in _setup
    self._correlations = self._calculate_correlations(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 375, in _calculate_correlations
    dataset.channel_names)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/misc/__init__.py", line 100, in resolve_channels
    raise ValueError('No channel exists with the specified name.')
ValueError: No channel exists with the specified name.
```

**Comment by nbdanielson** [comment]
Hi,
Not sure about your first error at the moment, but the second error looks like you didn’t match the channel_name attribute in your dataset with the one hard-coded in the example we posted.  That code is intended to run on the example data we provide.  You’ll need to edit the channel_names parameter in the segmentation_approach variable to match whatever channel name you used to init your dataset

**Comment by eflister** [comment]
ha ha, just realized that -- removing the channel name yields the same error as in STICA

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/imaging.py", line 768, in segment
    rois = strategy.segment(self)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 46, in segment
    rois = self._segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 88, in checked_func
    return func(self, dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/ca1pc.py", line 265, in _segment
    return self._normcut_method.segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 46, in segment
    rois = self._segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 88, in checked_func
    return func(self, dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 485, in _segment
    affinity = params['affinity_method'].calculate(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 391, in calculate
    self._setup(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/ca1pc.py", line 152, in _setup
    super(AffinityMatrixCA1PC, self)._setup(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 388, in _setup
    self._correlations = self._calculate_correlations(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 378, in _calculate_correlations
    num_pcs=self._params['num_pcs'], verbose=self._params['verbose'])
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 294, in _offset_corrs
    verbose=verbose)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/oPCA.py", line 291, in dataset_opca
    DatasetIterable(dataset, ch), num_pcs=num_pcs, verbose=verbose)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/oPCA.py", line 89, in EM_oPCA
    for X in (data):
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/oPCA.py", line 244, in __iter__
    frame[..., self.channel].reshape(-1) - self.means)
ValueError: operands could not be broadcast together with shapes (200,) (20,) 
```

**Comment by pkaifosh** [comment]
> http://www.losonczylab.org/sima/1.2/tutorial.html#creating-an-imagingdataset-object
> says:
>"raw imaging data used to initialize the ImagingDataset object must be packaged into a list of lists, whose >first index runs over the cycles and whose second index runs over the channels"

Good catch. This inaccuracy is a vestige from the sima 0.x versions.

**Comment by eflister** [comment]
same occurs for sequence initialized with HDF5 (exported from matlab, tried both `save(...'-v7.3)`, which is "[HDF5 based](http://www.mathworks.com/help/matlab/import_export/mat-file-versions.html)" or [`h5create/h5write`](http://www.mathworks.com/help/matlab/high-level-functions.html))

incidentally, in either case, `sima.Sequence.create('HDF5', ..., 'yxt')` results in a `seq` with the wrong shape -- the matlab data were `10x20x100` (rows x cols x frames), and the `seq` is `(10, 1, 100, 20, 1)`, but should be `(100, 1, 10, 20, 1)`.  `scipy.io.loadmat()` correctly retains the original shape for -v7 .mat files.  shall i create a new issue for this?

**Comment by eflister** [comment]
`example_hdf5` in `sima.misc` imports to the correct shape, but attempting to segment results in same errors described.

shape appears to be correct only because your example h5 data is saved as 'tyx,' not 'yxt'?  the doc say 'yxt' [here](http://www.losonczylab.org/sima/1.2/tutorial.html#hdf5-files) and [four times here](http://www.losonczylab.org/sima/1.2/api/sequence.html).

in matlab:
```
>> d=h5info('/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/misc/../tests/data/example.h5')

d = 

      Filename: '/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/tests/data/example.h5'
          Name: '/'
        Groups: []
      Datasets: [1x1 struct]
     Datatypes: []
         Links: []
    Attributes: []

>> d.Datasets

ans = 

          Name: 'imaging'
      Datatype: [1x1 struct]
     Dataspace: [1x1 struct]
     ChunkSize: []
     FillValue: 0
       Filters: []
    Attributes: []

>> d.Datasets.Datatype

ans = 

          Name: ''
         Class: 'H5T_INTEGER'
          Type: 'H5T_STD_U16LE'
          Size: 2
    Attributes: []

>> d.Datasets.Dataspace

ans = 

       Size: [20 256 128]
    MaxSize: [20 256 128]
       Type: 'simple'
```

my truly yxt data:
```
>> d=h5info('data.h5')

d = 

      Filename: '/Users/eflister/Desktop/data.h5'
          Name: '/'
        Groups: []
      Datasets: [1x1 struct]
     Datatypes: []
         Links: []
    Attributes: []

>> d.Datasets

ans = 

          Name: 'data'
      Datatype: [1x1 struct]
     Dataspace: [1x1 struct]
     ChunkSize: []
     FillValue: 0
       Filters: []
    Attributes: []

>> d.Datasets.Datatype

ans = 

          Name: ''
         Class: 'H5T_FLOAT'
          Type: 'H5T_IEEE_F64LE'
          Size: 8
    Attributes: []

>> d.Datasets.Dataspace

ans = 

       Size: [10 20 100]
    MaxSize: [10 20 100]
       Type: 'simple'
```

**Comment by jzaremba** [comment]
I tried running this against 1.2 and master on Linux and Windows and it worked fine for me. Does this script give you the error you're having?

```python
import sima
from sima import segment
import numpy as np

arr = np.random.random((100, 1, 10, 20, 1))

seq = sima.Sequence.create('ndarray', arr)

ds = sima.ImagingDataset([seq], 'test.sima')

ca1pc_segment = sima.segment.PlaneCA1PC(
    channel='0',
    num_pcs=30,
    max_dist=(3, 6),
    spatial_decay=(3, 6),
    cut_max_pen=0.10,
    cut_min_size=50,
    cut_max_size=150,
    x_diameter=14,
    y_diameter=7,
    circularity_threhold=.5,
    min_roi_size=20,
    min_cut_size=40
)

stica_segment = segment.STICA(components=2, verbose=True)

ds.segment(ca1pc_segment, 'ca1pc_rois')
ds.segment(stica_segment, 'stica_rois')
```

**Comment by eflister** [comment]
it is something about existing .sima savedirs interfering with newly initialized ImagingDatasets that use the same savedir but have different shape.  took a long time to isolate this -- spent a long time checking different data types, data ranges, your example tiffs, file formats, etc.

the script you sent works, until i increase the num_rows or num_cols of arr (does not occur if decrease, or change num_frames!).  then i get the following error until i either delete the saved .sima directory or use a new one:
```
Traceback (most recent call last):
  File "jz.py", line 26, in <module>
    ds.segment(ca1pc_segment, 'ca1pc_rois')
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/imaging.py", line 768, in segment
    rois = strategy.segment(self)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 46, in segment
    rois = self._segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 88, in checked_func
    return func(self, dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/ca1pc.py", line 265, in _segment
    return self._normcut_method.segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 46, in segment
    rois = self._segment(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/segment.py", line 88, in checked_func
    return func(self, dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 485, in _segment
    affinity = params['affinity_method'].calculate(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 391, in calculate
    self._setup(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/ca1pc.py", line 152, in _setup
    super(AffinityMatrixCA1PC, self)._setup(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 388, in _setup
    self._correlations = self._calculate_correlations(dataset)
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 378, in _calculate_correlations
    num_pcs=self._params['num_pcs'], verbose=self._params['verbose'])
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 299, in _offset_corrs
    for u, v, w, x in pixel_pairs
  File "/Users/eflister/Library/Python/2.7/lib/python/site-packages/sima/segment/normcut.py", line 299, in <dictcomp>
    for u, v, w, x in pixel_pairs
IndexError: index 20 is out of bounds for axis 1 with size 20
```
i can also recover my original error by removing the ca1pc parameters.

**Comment by jzaremba** [comment]
Thanks for figuring that out, I can reproduce the problem now.

I think I see the issue. If you initialize a new dataset in a path that already exits, we just throw that "Overwrite?" message but don't actually delete the directory. As things get changed/saved they overwrite as needed.

This is a problem when you call dataset.time_averages on the new dataset and the old time_averages.pkl gets loaded instead of being re-calc'd and now the new dataset dimensions are out of sync with the time average.

A few options:

1. Get rid of the "Overwrite?" message and raise an exception if the path is not empty.
2. Possibly along with the previous option, add a 'overwrite=False' option to the ImagingDataset init.
3. Leave the message, but delete the old directory if the user says 'y'.

I'm not a huge fan of the overwrite prompt as it is, so I think I'd vote for 1 (maybe w/ 2), but I think any of them would work.

**Comment by pkaifosh** [comment]
I vote for the 1 with 2 option. This should be done for both the ```__init__()``` and ```save()``` methods.

**Comment by eflister** [comment]
what will happen if overwrite=True?  not the current behavior (when user responds 'y'), right?  option 3 will happen?

**Comment by pkaifosh** [comment]
As I understand, the idea is to add an extra argument ```overwrite``` to the ```__init__()`` and ```save()``` methods. This argument will default to ```False```, in which case an exception will be raised if the savedir already exists. If the argument is set to ```True```, however, then then any existing directory with the same path will be fully deleted and overwritten.
