### ISSUE TITLE
unstated requirements on data shape

### ISSUE THREAD

**Issue by eflister** [losonczylab/sima#180]
if i try to run with an (admittedly unrealistic) test sequence of shape (5, 1, 3, 4, 1), STICA segmentation errors cryptically:
```
performing PCA... 
C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\skimage\filter\__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13. 
  warn(skimage_deprecation('The `skimage.filter` module has been renamed ' 
Traceback (most recent call last): 
  File "tosima.py", line 52, in <module> 
    rois = dataset.segment(segmentation_approach, 'auto_ROIs') 
  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\sima\imaging.py", line 768, in segment 
    rois = strategy.segment(self) 
  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\sima\segment\segment.py", line 46, in segment 
    rois = self._segment(dataset) 
  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\sima\segment\stica.py", line 195, in _segment 
    dataset, channel, components[-1] + 1, path=pca_path) 
  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\sima\segment\oPCA.py", line 291, in dataset_opca 
    DatasetIterable(dataset, ch), num_pcs=num_pcs, verbose=verbose) 
  File "C:\Users\nlab\Downloads\WinPython-64bit-2.7.9.5\python-2.7.9.amd64\lib\site-packages\sima\segment\oPCA.py", line 108, in EM_oPCA 
    _opca._Z_update(Z, U, data) 
  File "sima\segment\_opca.pyx", line 82, in sima.segment._opca._Z_update (sima/segment/_opca.c:3260) 
ValueError: operands could not be broadcast together with shapes (75,12) (4,12) (75,12) 
```

**Comment by pkaifosh** [comment]
Yes, this has to do with the number of PCs being asked for being greater than the number of frames. At the very least, we should make the error message more clear.
