### ISSUE TITLE
Assertion error with multiplane correction

### ISSUE THREAD

**Issue by ifittakesallnight** [losonczylab/sima#194]
I am trying to 3D motion correct a series of volumes--a sequence of shape (400, 189, 360, 100, 1) in which the 189 planes of each volume are closely spaced images. While running a very recent download of SIMA on Python 2.7 on Debian, I get an assertion error like this:

>>> mc_approach = sima.motion.HiddenMarkov3D(granularity='plane', max_displacement=[30,30,30], n_processes=1, verbose=True)
>>> dataset = mc_approach.correct([seq], 'mc.sima')
Estimating model parameters.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/randy/.local/lib/python2.7/site-packages/sima/motion/motion.py", line 116, in correct
    displacements = self.estimate(sima.ImagingDataset(mc_sequences, None))
  File "/home/randy/.local/lib/python2.7/site-packages/sima/motion/motion.py", line 59, in estimate
    shifts = self._estimate(dataset)
  File "/home/randy/.local/lib/python2.7/site-packages/sima/motion/hmm.py", line 415, in _estimate
    references, variances = _whole_frame_shifting(dataset, shifts)
  File "/home/randy/.local/lib/python2.7/site-packages/sima/motion/hmm.py", line 111, in _whole_frame_shifting
    assert np.all(min_shifts == 0)
AssertionError

I get the same error even if I change the granularity to frame or row. Any ideas about a work-around or fix?

R.Bruno

**Comment by pkaifosh** [comment]
Thanks for the report. This is the first time I have seen this error.
Are you able to provide us with a link to download the dataset and a
file with the code that you used to produce the error?

ifittakesallnight wrote:
