### ISSUE TITLE
ROIBuddy Cannot load

### ISSUE THREAD

**Issue by Ron89** [losonczylab/sima#210]
After successfully installed ROIBuddy with
```
pip2 install roibuddy --user
mv ~/.local/bin/roibuddy ~/.local/bin/roibuddy2
pip3 install roibuddy --user
mv ~/.local/bin/roibuddy ~/.local/bin/roibuddy3
```
If I use Python 2 version of ROIBuddy, `roibuddy2`, following error occurs
```
home/chong/.local/lib/python2.7/site-packages/skimage/filter/__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
Traceback (most recent call last):
  File "/home/chong/.local/bin/roibuddy2", line 7, in <module>
    from roibuddy.roi_buddy import main
  File "/home/chong/.local/lib/python2.7/site-packages/roibuddy/roi_buddy.py", line 32, in <module>
    from guidata import qthelpers
  File "/home/chong/.local/lib/python2.7/site-packages/guidata/__init__.py", line 541, in <module>
    import guidata.config
  File "/home/chong/.local/lib/python2.7/site-packages/guidata/config.py", line 15, in <module>
    from guidata.configtools import add_image_module_path, get_translation
  File "/home/chong/.local/lib/python2.7/site-packages/guidata/configtools.py", line 22, in <module>
    from guidata.qt.QtGui import (QFont, QLabel, QPixmap, QIcon, QHBoxLayout,
  File "/home/chong/.local/lib/python2.7/site-packages/guidata/qt/__init__.py", line 25, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1
```

And if I use Python 3 version of ROIBuddy, `roibuddy3`, following error occurs
```
Traceback (most recent call last):
  File "/home/chong/.local/bin/roibuddy3", line 9, in <module>
    load_entry_point('roibuddy==1.0.0', 'gui_scripts', 'roibuddy')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/chong/.local/lib/python3.5/site-packages/roibuddy/__init__.py", line 1, in <module>
    from roiBuddyUI import *
ImportError: No module named 'roiBuddyUI'
```

Eventually nothing works...

I am using Arch Linux with the latest pyqt for both Python2 and Python3. What could be the issue? Is there any way to fix it?

**Comment by Ron89** [comment]
I have managed to make Python3 version of roiBuddy to open correctly. I am going to test its functionality further. If I am to make a pull request, where should I send it to? Do you have a Python3 branch? Or do I simply send it to the master branch?

**Comment by Ron89** [comment]
Sorry, I see ROIBuddy is a separate project. I'll close it and move it there.
