### ISSUE TITLE
multiprocessing on Windows

### ISSUE THREAD

**Issue by pkaifosh** [losonczylab/sima#53]
From Tim:

I just updated my repository and re-ran the test suite and
there's a fourth error that seems related to Nathan's commit from 2
days ago:

```
======================================================================
ERROR: test__hmm.Test_HiddenMarkov2D.test_correlation_based_correction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\tamachado\Documents\My
Dropbox\Code\Python\sima\build\testenv\Lib\site-packages\sima\motion\tests\test__hmm.py",
line 189, in test_correlation_based_correction
    shifts = self.hm2d._correlation_based_correction(self.dataset)
  File "C:\Users\tamachado\Documents\My
Dropbox\Code\Python\sima\build\testenv\Lib\site-packages\sima\motion\_hmm.py",
line 416, in _correlation_based_correction
    max_displacement, n_processes=n_processes).estimate(dataset)
  File "C:\Users\tamachado\Documents\My
Dropbox\Code\Python\sima\build\testenv\Lib\site-packages\sima\motion\motion.py",
line 36, in estimate
    return self._make_nonnegative(self._estimate(dataset))
  File "C:\Users\tamachado\Documents\My
Dropbox\Code\Python\sima\build\testenv\Lib\site-packages\sima\motion\frame_align.py",
line 95, in _estimate
    params.n_processes)
  File "C:\Users\tamachado\Documents\My
Dropbox\Code\Python\sima\build\testenv\Lib\site-packages\sima\motion\frame_align.py",
line 188, in _frame_alignment_base
    next(map_generator)
  File "c:\Python27\lib\multiprocessing\pool.py", line 655, in next
    raise value
AttributeError: __exit__
```

**Comment by pkaifosh** [comment]
@tamachado This code has changed a lot since the bug was reported. If you pull the latest version, is it still causing problems?

**Comment by pkaifosh** [comment]
After pull request #103, this won't be a problem at least for the default case, so we won't let this hold back the 1.0 release. We will keep the issue open until we check things out with Appveyer.

**Comment by pkaifosh** [comment]
The tests seem to be passing okay on Appveyor.
